apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # base64-encoded value of "rootpassword"
  mysql-user: Z2FicmllbA==  # base64-encoded value of "gabriel"
  mysql-password: bmFtZXNwYXhlQDEyMw==  # base64-encoded value of "namespaxe@123"
