FROM mysql:8.0

# Copy SQL initialization script
COPY db-init.sql /docker-entrypoint-initdb.d/

# Ensure the initialization script has the right permissions
RUN chmod 644 /docker-entrypoint-initdb.d/db-init.sql

# Fix permissions and ensure the data directory is clean
USER root
RUN rm -rf /var/lib/mysql/* && chown -R mysql:mysql /var/lib/mysql /docker-entrypoint-initdb.d

# Switch back to the MySQL user
USER mysql

EXPOSE 3306

# Use the default CMD provided by the MySQL image
CMD ["mysqld"]
