name: Build and Push MySQL Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NS_USERNAME }}
          password: ${{ secrets.NS_PASSWORD }}

      # Step 4: Build and push the MySQL Docker image
      - name: Build and push MySQL Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.mysql  # Assuming your database Dockerfile is named Dockerfile.mysql
          tags: ${{ secrets.NS_USERNAME }}/php_app_mysql:1.4
          push: true

      # Step 5: Logout from Docker Hub
      - name: Logout from Docker Hub
        run: docker logout
